import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import ScrollToTopButton from "./components/ScrollToTopButton";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
  fallback: ["Inter", "Helvetica", "sans-serif"],
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
  fallback: ["Inter", "Helvetica", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: "next.js, web development, react",
  author: "Your Name",
  openGraph: {
    type: "website",
    url: "https://yourwebsite.com",
    title: "Your Website Title",
    description: "A description of your website for social sharing.",
    images: [
      {
        url: "/path-to-image.jpg",
        width: 800,
        height: 600,
        alt: "Image description",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
      >
        <Header />
        <main>{children}</main>

        <Footer />
        <ScrollToTopButton />
      </body>
    </html>
  );
}
